---
include:
  - project: 'oberhaus77/renovate-test'
    ref: 1.0.0
    file: '/.gitlab-ci-template.yml'

stages:
  - simple

test:
  image: alpine:latest@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
  stage: simple
  script:
    - echo hello
    - sleep 300

